<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8BUMFP7" failures="1" tests="8" name="testNGpractice.Regressionsuite" time="33.873" errors="0" timestamp="2022-06-03T11:52:07 IST" skipped="1">
  <testcase classname="testNGpractice.Regressionsuite" name="testcase1" time="5.554">
    <failure message="expected [MainHMRR] but found [MainHMR]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [MainHMRR] but found [MainHMR]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNGpractice.Regressionsuite.testcase1(Regressionsuite.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase2" time="5.055"/>
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase3" time="4.052"/>
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase5" time="3.696"/>
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase6" time="3.845"/>
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase7" time="4.040">
    <skipped/>
  </testcase> <!-- testcase7 -->
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase8" time="6.965"/>
  <system-out/>
  <testcase classname="testNGpractice.Regressionsuite" name="testcase10" time="0.666"/>
  <system-out/>
</testsuite> <!-- testNGpractice.Regressionsuite -->
